### ISSUE TITLE
TODOs in `plonk/composer/composer_base.rs`

### ISSUE THREAD

**Issue by Autoparallel** [laudiacay/barustenberg#38]
# Composer Base

Here are some tasks, my friends!

- [ ] Implement `ComposerType::create_manifest()`
- [ ] Implement `ComposerBase::compute_wire_copy_cycles()`
- [ ] Implement `ComposerBase::compute_sigma_permutations()`

---

Then we should add in the accompanying tests from [here](https://gist.github.com/shuklaayush/d3952ae12124082b28aa71834e3cafe1).

**Comment by JDLBeckman** [comment]
For `ComposerType::create_manifest`, I think what we actually want is for `StandardComposer::create_manifest` to be an associated function instead of a method, then for `verifier/test.rs` to use that function instead.

The other two have implementations that are commented out, @laudiacay want me to try and finish them?

**Comment by Autoparallel** [comment]
@JDLBeckman want me to go ahead and assign?

**Comment by JDLBeckman** [comment]
@Autoparallel Please do!

**Comment by laudiacay** [comment]
Yeah SGTM!!

**Comment by Autoparallel** [comment]
@JDLBeckman I assigned. Can you update the tasks for me in a comment?

**Comment by laudiacay** [comment]
oh yo @JDLBeckman how's it going

**Comment by laudiacay** [comment]
still a valid issue as of sept 18

**Comment by laudiacay** [comment]
closed in #84
